### ISSUE TITLE
Does this require existing smokeping

### ISSUE THREAD

**Issue by goetzk** [cloudalchemy/ansible-smokeping_prober#9]
Hi,
I'm considering using this role to run on a server which already has smokeping installed and configured. Am I able to use this role to export my existing data to prometheus or does this role invoke an existing smokeping install to monitor a different set of hosts?

thanks,

**Comment by paulfantom** [comment]
This role installs and manages https://github.com/SuperQ/smokeping_prober. It doesn't have anything to do with https://oss.oetiker.ch/smokeping/ so you won't be able to export existing data using this role.

**Comment by goetzk** [comment]
Sorry for not responding - I forgot about the reply until the bot kicked in (yay for the bot?).

Thanks for your response @paulfantom , that clears things up!

Karl.
